### ISSUE TITLE
android crash  filterted logcat

### ISSUE THREAD

**Issue by sahilsharma-dot** [bakjos/FFMPEGMedia#22]
hi @ bakjos 
the plugin  works great inside editor with ffmpeg  player but causes  crash when opened in  android api 29 with ue4.24.
the crash  logs are here.from these logs i infer that it might the loading phase of ffmpeg module which is pre-loading screen  or  the cpp-11 lirary  of ffmpeg may have gotten old .
here are the logs from api-29.
the app package is  com.kalasa.porg.any idea what is wrong
C:\NVPACK\android-sdk-windows\platform-tools>adb shell "logcat --pid=$(pidof -s com.kalasa.porg)"
--------- beginning of main
10-15 21:01:45.967 25624 25624 I com.kalasa.por: Late-enabling -Xcheck:jni
10-15 21:01:46.002 25624 25624 E com.kalasa.por: Unknown bits set in runtime_flags: 0x8000
10-15 21:01:46.004 25624 25624 I com.kalasa.por: Reinit property: dalvik.vm.checkjni= false
10-15 21:01:46.015 25624 25624 W re-initialized>: type=1400 audit(0.0:1145579): avc: denied { read } for pid=25624 name="u:object_r:mmi_prop:s0" dev="tmpfs" ino=15402 scontext=u:r:untrusted_app:s0:c133,c262,c512,c768 tcontext=u:object_r:mmi_prop:s0 tclass=file permissive=0
10-15 21:01:46.019 25624 25624 E libc    : Access denied finding property "runtime.mmitest.isrunning"
--------- beginning of system
10-15 21:01:46.021 25624 25624 D ActivityThread: Attach thread to application
10-15 21:01:46.275 25624 25624 I com.kalasa.por: QarthPatchMonintor::Init
10-15 21:01:46.275 25624 25624 I com.kalasa.por:
10-15 21:01:46.275 25624 25624 I com.kalasa.por: QarthPatchMonintor::StartWatch
10-15 21:01:46.275 25624 25624 I com.kalasa.por:
10-15 21:01:46.275 25624 25624 I com.kalasa.por: QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
10-15 21:01:46.275 25624 25624 I com.kalasa.por:
10-15 21:01:46.275 25624 25624 I com.kalasa.por: QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/com.kalasa.porg
10-15 21:01:46.275 25624 25624 I com.kalasa.por:
10-15 21:01:46.275 25624 25624 I com.kalasa.por: QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
10-15 21:01:46.275 25624 25624 I com.kalasa.por:
10-15 21:01:46.275 25624 25624 I com.kalasa.por: QarthPatchMonintor::Run
10-15 21:01:46.275 25624 25624 I com.kalasa.por:
10-15 21:01:46.279 25624 25659 I com.kalasa.por: QarthPatchMonintor::Reading
10-15 21:01:46.279 25624 25659 I com.kalasa.por:
10-15 21:01:46.279 25624 25659 I com.kalasa.por: QarthPatchMonintor::CheckNotifyEvent
10-15 21:01:46.279 25624 25659 I com.kalasa.por:
10-15 21:01:46.279 25624 25659 I com.kalasa.por: QarthPatchMonintor::CheckNotifyEvent before read
10-15 21:01:46.279 25624 25659 I com.kalasa.por:
10-15 21:01:46.280 25624 25644 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.kalasa.porg#11669#256
10-15 21:01:46.281 25624 25644 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.kalasa.porg#11669#0
10-15 21:01:46.284 25624 25624 I MultiDex: VM with version 2.1.0 has multidex support
10-15 21:01:46.284 25624 25624 I MultiDex: Installing application
10-15 21:01:46.284 25624 25624 I MultiDex: VM has multidex support, MultiDex support library is disabled.
10-15 21:01:46.286 25624 25644 I AwareBitmapCacher: init processName:com.kalasa.porg pid=25624 uid=11669
10-15 21:01:46.299 25624 25660 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@9130914
10-15 21:01:46.300 25624 25660 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@35725bd
10-15 21:01:46.364 25624 25624 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
10-15 21:01:46.365 25624 25624 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
10-15 21:01:46.365 25624 25624 I FirebaseInitProvider: FirebaseApp initialization successful
10-15 21:01:46.368 25624 25671 D HwFrameworkSecurityPartsFactory: HwFrameworkSecurityPartsFactory in.
10-15 21:01:46.368 25624 25671 I HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
10-15 21:01:46.404 25624 25671 I FA      : Collection disabled with firebase_analytics_collection_deactivated=1
10-15 21:01:46.404 25624 25624 V ActivityThread: callActivityOnCreate
10-15 21:01:46.404 25624 25671 I FA      : App measurement is starting up, version: 15300
10-15 21:01:46.404 25624 25671 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
10-15 21:01:46.405 25624 25671 I FA      : To enable faster debug mode event logging run:
10-15 21:01:46.405 25624 25671 I FA      :   adb shell setprop debug.firebase.analytics.app com.kalasa.porg
10-15 21:01:46.457 25624 25624 V HwWidgetFactory: : successes to get AllImpl object and return....
10-15 21:01:46.468 25624 25624 D ActivityThread: add activity client record, r= ActivityRecord{a39e6d3 token=android.os.BinderProxy@1fdaf99 {com.kalasa.porg/com.epicgames.ue4.SplashActivity}} token= android.os.BinderProxy@1fdaf99
10-15 21:01:46.487 25624 25624 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@92dc210
10-15 21:01:46.559 25624 25624 D AndroidRuntime: Shutting down VM
10-15 21:01:46.559 25624 25624 I QarthLog: [PatchStore] createDisableExceptionQarthFile
10-15 21:01:46.559 25624 25624 I QarthLog: [PatchStore] create disable file for com.kalasa.porg uid is 11669
--------- beginning of crash
10-15 21:01:46.561 25624 25624 E AndroidRuntime: FATAL EXCEPTION: main
10-15 21:01:46.561 25624 25624 E AndroidRuntime: Process: com.kalasa.porg, PID: 25624
10-15 21:01:46.561 25624 25624 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1668)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at com.epicgames.ue4.GameActivity.<clinit>(GameActivity.java:6829)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1257)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3685)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:213)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8178)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-15 21:01:46.561 25624 25624 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
10-15 21:01:46.570 25624 25624 I Process : Sending signal. PID: 25624 SIG: 9

**Comment by bakjos** [comment]
@sahilsharma-dot I think this has something to do with the NDK version you're using or with the architecture of your phone/emulator, what's the arch? in the generated apk do you see a folder for your arch inside the lib folder?

**Comment by sahilsharma-dot** [comment]
thanks for replying so quick Mr bakjos
yes I have both armevi8a and armevi7a. I did remove ×64 and 86 libraries
but with those two also I get the same result.

**Comment by sahilsharma-dot** [comment]
my ndk version is 21
